import React from 'react';

import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';
import { linkTo } from '@storybook/addon-links';
import {TextBlock, MediaBlock, TextRow, RectShape, RoundShape} from 'react-placeholder/lib/placeholders';

const stories = storiesOf('Semantic UI/Element/Font Icon', module);


stories.add('Accessibility', () => (
  <div className="ui segment">
    <i class="american sign language interpreting icon"></i>
    <i class="assistive listening systems icon"></i>
    <i class="audio description icon"></i>
    <i class="blind icon"></i>
    <i class="braille icon"></i>
    <i class="closed captioning icon"></i>
    <i class="closed captioning outline icon"></i>
    <i class="deaf icon"></i>
    <i class="low vision icon"></i>
    <i class="phone volume icon"></i>
    <i class="question circle icon"></i>
    <i class="question circle outline icon"></i>
    <i class="sign language icon"></i>
    <i class="tty icon"></i>
    <i class="universal access icon"></i>
    <i class="wheelchair icon"></i>
  </div>
));

stories.add('Arrows', () => (
  <div className="ui segment">
    <i class="angle double down icon"></i>
    <i class="angle double left icon"></i>
    <i class="angle double right icon"></i>
    <i class="angle double up icon"></i>
    <i class="angle down icon"></i>
    <i class="angle left icon"></i>
    <i class="angle right icon"></i>
    <i class="angle up icon"></i>
    <i class="arrow alternate circle down icon"></i>
    <i class="arrow alternate circle down outline icon"></i>
    <i class="arrow alternate circle left icon"></i>
    <i class="arrow alternate circle left outline icon"></i>
    <i class="arrow alternate circle right icon"></i>
    <i class="arrow alternate circle right outline icon"></i>
    <i class="arrow alternate circle up icon"></i>
    <i class="arrow alternate circle up outline icon"></i>
    <i class="arrow circle down icon"></i>
    <i class="arrow circle left icon"></i>
    <i class="arrow circle right icon"></i>
    <i class="arrow circle up icon"></i>
    <i class="arrow down icon"></i>
    <i class="arrow left icon"></i>
    <i class="arrow right icon"></i>
    <i class="arrow up icon"></i>
    <i class="arrows alternate icon"></i>
    <i class="arrows alternate horizontal icon"></i>
    <i class="arrows alternate vertical icon"></i>
    <i class="caret down icon"></i>
    <i class="caret left icon"></i>
    <i class="caret right icon"></i>
    <i class="caret square down icon"></i>
    <i class="caret square down outline icon"></i>
    <i class="caret square left icon"></i>
    <i class="caret square left outline icon"></i>
    <i class="caret square right icon"></i>
    <i class="caret square right outline icon"></i>
    <i class="caret square up icon"></i>
    <i class="caret square up outline icon"></i>
    <i class="caret up icon"></i>
    <i class="cart arrow down icon"></i>
    <i class="chart line icon"></i>
    <i class="chevron circle down icon"></i>
    <i class="chevron circle left icon"></i>
    <i class="chevron circle right icon"></i>
    <i class="chevron circle up icon"></i>
    <i class="chevron down icon"></i>
    <i class="chevron left icon"></i>
    <i class="chevron right icon"></i>
    <i class="chevron up icon"></i>
    <i class="cloud download icon"></i>
    <i class="cloud upload icon"></i>
    <i class="download icon"></i>
    <i class="exchange alternate icon"></i>
    <i class="expand arrows alternate icon"></i>
    <i class="external alternate icon"></i>
    <i class="external square alternate icon"></i>
    <i class="hand point down icon"></i>
    <i class="hand point down outline icon"></i>
    <i class="hand point left icon"></i>
    <i class="hand point left outline icon"></i>
    <i class="hand point right icon"></i>
    <i class="hand point right outline icon"></i>
    <i class="hand point up icon"></i>
    <i class="hand point up outline icon"></i>
    <i class="hand pointer icon"></i>
    <i class="hand pointer outline icon"></i>
    <i class="history icon"></i>
    <i class="level down alternate icon"></i>
    <i class="level up alternate icon"></i>
    <i class="location arrow icon"></i>
    <i class="long arrow alternate down icon"></i>
    <i class="long arrow alternate left icon"></i>
    <i class="long arrow alternate right icon"></i>
    <i class="long arrow alternate up icon"></i>
    <i class="mouse pointer icon"></i>
    <i class="play icon"></i>
    <i class="random icon"></i>
    <i class="recycle icon"></i>
    <i class="redo icon"></i>
    <i class="redo alternate icon"></i>
    <i class="reply icon"></i>
    <i class="reply all icon"></i>
    <i class="retweet icon"></i>
    <i class="share icon"></i>
    <i class="share square icon"></i>
    <i class="share square outline icon"></i>
    <i class="sign in alternate icon"></i>
    <i class="sign out alternate icon"></i>
    <i class="sort icon"></i>
    <i class="sort alphabet down icon"></i>
    <i class="sort alphabet up icon"></i>
    <i class="sort amount down icon"></i>
    <i class="sort amount up icon"></i>
    <i class="sort down icon"></i>
    <i class="sort numeric down icon"></i>
    <i class="sort numeric up icon"></i>
    <i class="sort up icon"></i>
    <i class="sync icon"></i>
    <i class="sync alternate icon"></i>
    <i class="text height icon"></i>
    <i class="text width icon"></i>
    <i class="undo icon"></i>
    <i class="undo alternate icon"></i>
    <i class="upload icon"></i>
  </div>
));

stories.add('Audio & Video', () => (
  <div className="ui segment">
    <i class="audio description icon"></i>
    <i class="backward icon"></i>
    <i class="circle icon"></i>
    <i class="circle outline icon"></i>
    <i class="closed captioning icon"></i>
    <i class="closed captioning outline icon"></i>
    <i class="compress icon"></i>
    <i class="eject icon"></i>
    <i class="expand icon"></i>
    <i class="expand arrows alternate icon"></i>
    <i class="fast backward icon"></i>
    <i class="fast forward icon"></i>
    <i class="file audio icon"></i>
    <i class="file audio outline icon"></i>
    <i class="file video icon"></i>
    <i class="file video outline icon"></i>
    <i class="film icon"></i>
    <i class="forward icon"></i>
    <i class="headphones icon"></i>
    <i class="microphone icon"></i>
    <i class="microphone slash icon"></i>
    <i class="music icon"></i>
    <i class="pause icon"></i>
    <i class="pause circle icon"></i>
    <i class="pause circle outline icon"></i>
    <i class="phone volume icon"></i>
    <i class="play icon"></i>
    <i class="play circle icon"></i>
    <i class="play circle outline icon"></i>
    <i class="podcast icon"></i>
    <i class="random icon"></i>
    <i class="redo icon"></i>
    <i class="redo alternate icon"></i>
    <i class="rss icon"></i>
    <i class="rss square icon"></i>
    <i class="step backward icon"></i>
    <i class="step forward icon"></i>
    <i class="stop icon"></i>
    <i class="stop circle icon"></i>
    <i class="stop circle outline icon"></i>
    <i class="sync icon"></i>
    <i class="sync alternate icon"></i>
    <i class="undo icon"></i>
    <i class="undo alternate icon"></i>
    <i class="video icon"></i>
    <i class="volume down icon"></i>
    <i class="volume off icon"></i>
    <i class="volume up icon"></i>
  </div>
));

stories.add('Business', () => (
  <div className="ui segment">
    <i class="address book icon"></i>
    <i class="address book outline icon"></i>
    <i class="address card icon"></i>
    <i class="address card outline icon"></i>
    <i class="archive icon"></i>
    <i class="balance scale icon"></i>
    <i class="birthday cake icon"></i>
    <i class="book icon"></i>
    <i class="briefcase icon"></i>
    <i class="building icon"></i>
    <i class="building outline icon"></i>
    <i class="bullhorn icon"></i>
    <i class="bullseye icon"></i>
    <i class="calculator icon"></i>
    <i class="calendar icon"></i>
    <i class="calendar outline icon"></i>
    <i class="calendar alternate icon"></i>
    <i class="calendar alternate outline icon"></i>
    <i class="certificate icon"></i>
    <i class="chart area icon"></i>
    <i class="chart bar icon"></i>
    <i class="chart bar outline icon"></i>
    <i class="chart line icon"></i>
    <i class="chart pie icon"></i>
    <i class="clipboard icon"></i>
    <i class="clipboard outline icon"></i>
    <i class="coffee icon"></i>
    <i class="columns icon"></i>
    <i class="compass icon"></i>
    <i class="compass outline icon"></i>
    <i class="copy icon"></i>
    <i class="copy outline icon"></i>
    <i class="copyright icon"></i>
    <i class="copyright outline icon"></i>
    <i class="cut icon"></i>
    <i class="edit icon"></i>
    <i class="edit outline icon"></i>
    <i class="envelope icon"></i>
    <i class="envelope outline icon"></i>
    <i class="envelope open icon"></i>
    <i class="envelope open outline icon"></i>
    <i class="envelope square icon"></i>
    <i class="eraser icon"></i>
    <i class="fax icon"></i>
    <i class="file icon"></i>
    <i class="file outline icon"></i>
    <i class="file alternate icon"></i>
    <i class="file alternate outline icon"></i>
    <i class="folder icon"></i>
    <i class="folder outline icon"></i>
    <i class="folder open icon"></i>
    <i class="folder open outline icon"></i>
    <i class="globe icon"></i>
    <i class="industry icon"></i>
    <i class="paperclip icon"></i>
    <i class="paste icon"></i>
    <i class="pen square icon"></i>
    <i class="pencil alternate icon"></i>
    <i class="percent icon"></i>
    <i class="phone icon"></i>
    <i class="phone square icon"></i>
    <i class="phone volume icon"></i>
    <i class="registered icon"></i>
    <i class="registered outline icon"></i>
    <i class="save icon"></i>
    <i class="save outline icon"></i>
    <i class="sitemap icon"></i>
    <i class="sticky note icon"></i>
    <i class="sticky note outline icon"></i>
    <i class="suitcase icon"></i>
    <i class="table icon"></i>
    <i class="tag icon"></i>
    <i class="tags icon"></i>
    <i class="tasks icon"></i>
    <i class="thumbtack icon"></i>
    <i class="trademark icon"></i>
  </div>
));

stories.add('Chess', () => (
  <div className="ui segment">
    <i class="chess icon"></i>
    <i class="chess bishop icon"></i>
    <i class="chess board icon"></i>
    <i class="chess king icon"></i>
    <i class="chess knight icon"></i>
    <i class="chess pawn icon"></i>
    <i class="chess queen icon"></i>
    <i class="chess rook icon"></i>
    <i class="square full icon"></i>
  </div>
));


stories.add('Code', () => (
  <div className="ui segment">
    <i class="archive icon"></i> 
    <i class="barcode icon"></i> 
    <i class="bath icon"></i> 
    <i class="bug icon"></i> 
    <i class="code icon"></i> 
    <i class="code branch icon"></i> 
    <i class="coffee icon"></i> 
    <i class="file icon"></i> 
    <i class="file outline icon"></i> 
    <i class="file alternate icon"></i> 
    <i class="file alternate outline icon"></i> 
    <i class="file code icon"></i> 
    <i class="file code outline icon"></i> 
    <i class="filter icon"></i> 
    <i class="fire extinguisher icon"></i> 
    <i class="folder icon"></i> 
    <i class="folder outline icon"></i> 
    <i class="folder open icon"></i> 
    <i class="folder open outline icon"></i> 
    <i class="keyboard icon"></i> 
    <i class="keyboard outline icon"></i> 
    <i class="microchip icon"></i> 
    <i class="qrcode icon"></i> 
    <i class="shield alternate icon"></i> 
    <i class="sitemap icon"></i> 
    <i class="terminal icon"></i> 
    <i class="user secret icon"></i> 
    <i class="window close icon"></i> 
    <i class="window close outline icon"></i> 
    <i class="window maximize icon"></i> 
    <i class="window maximize outline icon"></i> 
    <i class="window minimize icon"></i> 
    <i class="window minimize outline icon"></i> 
    <i class="window restore icon"></i> 
    <i class="window restore outline icon"></i>
  </div>
));

stories.add('Communication', () => (
  <div className="ui segment">
    <i class="address book icon"></i>
    <i class="address book outline icon"></i>
    <i class="address card icon"></i>
    <i class="address card outline icon"></i>
    <i class="american sign language interpreting icon"></i>
    <i class="assistive listening systems icon"></i>
    <i class="at icon"></i>
    <i class="bell icon"></i>
    <i class="bell outline icon"></i>
    <i class="bell slash icon"></i>
    <i class="bell slash outline icon"></i>
    <i class="bullhorn icon"></i>
    <i class="comment icon"></i>
    <i class="comment outline icon"></i>
    <i class="comment alternate icon"></i>
    <i class="comment alternate outline icon"></i>
    <i class="comments icon"></i>
    <i class="comments outline icon"></i>
    <i class="envelope icon"></i>
    <i class="envelope outline icon"></i>
    <i class="envelope open icon"></i>
    <i class="envelope open outline icon"></i>
    <i class="envelope square icon"></i>
    <i class="fax icon"></i>
    <i class="inbox icon"></i>
    <i class="language icon"></i>
    <i class="microphone icon"></i>
    <i class="microphone slash icon"></i>
    <i class="mobile icon"></i>
    <i class="mobile alternate icon"></i>
    <i class="paper plane icon"></i>
    <i class="paper plane outline icon"></i>
    <i class="phone icon"></i>
    <i class="phone square icon"></i>
    <i class="phone volume icon"></i>
    <i class="rss icon"></i>
    <i class="rss square icon"></i>
    <i class="tty icon"></i>
    <i class="wifi icon"></i>
  </div>
));

stories.add('Computers', () => (
  <div className="ui segment">
    <i class="desktop icon"></i>
    <i class="download icon"></i>
    <i class="hdd icon"></i>
    <i class="hdd outline icon"></i>
    <i class="headphones icon"></i>
    <i class="keyboard icon"></i>
    <i class="keyboard outline icon"></i>
    <i class="laptop icon"></i>
    <i class="microchip icon"></i>
    <i class="mobile icon"></i>
    <i class="mobile alternate icon"></i>
    <i class="plug icon"></i>
    <i class="power off icon"></i>
    <i class="print icon"></i>
    <i class="save icon"></i>
    <i class="save outline icon"></i>
    <i class="server icon"></i>
    <i class="tablet icon"></i>
    <i class="tablet alternate icon"></i>
    <i class="tv icon"></i>
    <i class="upload icon"></i>
  </div>
));

stories.add('Currency', () => (
  <div className="ui segment">
    <i class="dollar sign icon"></i>
    <i class="euro sign icon"></i>
    <i class="lira sign icon"></i>
    <i class="money bill alternate icon"></i>
    <i class="money bill alternate outline icon"></i>
    <i class="pound sign icon"></i>
    <i class="ruble sign icon"></i>
    <i class="rupee sign icon"></i>
    <i class="shekel sign icon"></i>
    <i class="won sign icon"></i>
    <i class="yen sign icon"></i>
  </div>
));

stories.add('Date & Time', () => (
  <div className="ui segment">
    <i class="bell icon"></i>
    <i class="bell outline icon"></i>
    <i class="bell slash icon"></i>
    <i class="bell slash outline icon"></i>
    <i class="calendar icon"></i>
    <i class="calendar outline icon"></i>
    <i class="calendar alternate icon"></i>
    <i class="calendar alternate outline icon"></i>
    <i class="calendar check icon"></i>
    <i class="calendar check outline icon"></i>
    <i class="calendar minus icon"></i>
    <i class="calendar minus outline icon"></i>
    <i class="calendar plus icon"></i>
    <i class="calendar plus outline icon"></i>
    <i class="calendar times icon"></i>
    <i class="calendar times outline icon"></i>
    <i class="clock icon"></i>
    <i class="clock outline icon"></i>
    <i class="hourglass icon"></i>
    <i class="hourglass outline icon"></i>
    <i class="hourglass end icon"></i>
    <i class="hourglass half icon"></i>
    <i class="hourglass start icon"></i>
    <i class="stopwatch icon"></i>
  </div>
));

stories.add('Design', () => (
  <div className='ui segment'>
    <i class="adjust icon"></i>
    <i class="clone icon"></i>
    <i class="clone outline icon"></i>
    <i class="copy icon"></i>
    <i class="copy outline icon"></i>
    <i class="crop icon"></i>
    <i class="crosshairs icon"></i>
    <i class="cut icon"></i>
    <i class="edit icon"></i>
    <i class="edit outline icon"></i>
    <i class="eraser icon"></i>
    <i class="eye icon"></i>
    <i class="eye dropper icon"></i>
    <i class="eye slash icon"></i>
    <i class="eye slash outline icon"></i>
    <i class="object group icon"></i>
    <i class="object group outline icon"></i>
    <i class="object ungroup icon"></i>
    <i class="object ungroup outline icon"></i>
    <i class="paint brush icon"></i>
    <i class="paste icon"></i>
    <i class="pencil alternate icon"></i>
    <i class="save icon"></i>
    <i class="save outline icon"></i>
    <i class="tint icon"></i>
  </div>

));

stories.add('Editors', () => (
  <div className='ui segment'>
    <i class="align center icon"></i>
    <i class="align justify icon"></i>
    <i class="align left icon"></i>
    <i class="align right icon"></i>
    <i class="bold icon"></i>
    <i class="clipboard icon"></i>
    <i class="clipboard outline icon"></i>
    <i class="clone icon"></i>
    <i class="clone outline icon"></i>
    <i class="columns icon"></i>
    <i class="copy icon"></i>
    <i class="copy outline icon"></i>
    <i class="cut icon"></i>
    <i class="edit icon"></i>
    <i class="edit outline icon"></i>
    <i class="eraser icon"></i>
    <i class="file icon"></i>
    <i class="file outline icon"></i>
    <i class="file alternate icon"></i>
    <i class="file alternate outline icon"></i>
    <i class="font icon"></i>
    <i class="heading icon"></i>
    <i class="i cursor icon"></i>
    <i class="indent icon"></i>
    <i class="italic icon"></i>
    <i class="linkify icon"></i>
    <i class="list icon"></i>
    <i class="list alternate icon"></i>
    <i class="list alternate outline icon"></i>
    <i class="list ol icon"></i>
    <i class="list ul icon"></i>
    <i class="outdent icon"></i>
    <i class="paper plane icon"></i>
    <i class="paper plane outline icon"></i>
    <i class="paperclip icon"></i>
    <i class="paragraph icon"></i>
    <i class="paste icon"></i>
    <i class="pencil alternate icon"></i>
    <i class="print icon"></i>
    <i class="quote left icon"></i>
    <i class="quote right icon"></i>
    <i class="redo icon"></i>
    <i class="redo alternate icon"></i>
    <i class="reply icon"></i>
    <i class="reply all icon"></i>
    <i class="share icon"></i>
    <i class="strikethrough icon"></i>
    <i class="subscript icon"></i>
    <i class="superscript icon"></i>
    <i class="sync icon"></i>
    <i class="sync alternate icon"></i>
    <i class="table icon"></i>
    <i class="tasks icon"></i>
    <i class="text height icon"></i>
    <i class="text width icon"></i>
    <i class="th icon"></i>
    <i class="th large icon"></i>
    <i class="th list icon"></i>
    <i class="trash icon"></i>
    <i class="trash alternate icon"></i>
    <i class="trash alternate outline icon"></i>
    <i class="underline icon"></i>
    <i class="undo icon"></i>
    <i class="undo alternate icon"></i>
    <i class="unlink icon"></i>
  </div>
));

stories.add('Files', () => (

  <div className='ui segment'>
    <i class="archive icon"></i>
    <i class="clone icon"></i>
    <i class="clone outline icon"></i>
    <i class="copy icon"></i>
    <i class="copy outline icon"></i>
    <i class="cut icon"></i> 
    <i class="file icon"></i> 
    <i class="file outline icon"></i> 
    <i class="file alternate icon"></i> 
    <i class="file alternate outline icon"></i> 
    <i class="file archive icon"></i> 
    <i class="file archive outline icon"></i> 
    <i class="file audio icon"></i> 
    <i class="file audio outline icon"></i> 
    <i class="file code icon"></i> 
    <i class="file code outline icon"></i> 
    <i class="file excel icon"></i> 
    <i class="file excel outline icon"></i> 
    <i class="file image icon"></i> 
    <i class="file image outline icon"></i> 
    <i class="file pdf icon"></i> 
    <i class="file pdf outline icon"></i> 
    <i class="file powerpoint icon"></i> 
    <i class="file powerpoint outline icon"></i> 
    <i class="file video icon"></i> 
    <i class="file video outline icon"></i> 
    <i class="file word icon"></i> 
    <i class="file word outline icon"></i> 
    <i class="folder icon"></i> 
    <i class="folder outline icon"></i> 
    <i class="folder open icon"></i> 
    <i class="folder open outline icon"></i> 
    <i class="paste icon"></i> 
    <i class="save icon"></i> 
    <i class="save outline icon"></i> 
    <i class="sticky note icon"></i> 
    <i class="sticky note outline icon"></i>
  </div>
));

stories.add('Gender', () => (
  <div className="ui segment">
    <i class="genderless icon"></i>
    <i class="mars icon"></i>
    <i class="mars double icon"></i>
    <i class="mars stroke icon"></i>
    <i class="mars stroke horizontal icon"></i>
    <i class="mars stroke vertical icon"></i>
    <i class="mercury icon"></i>
    <i class="neuter icon"></i>
    <i class="transgender icon"></i>
    <i class="transgender alternate icon"></i>
    <i class="venus icon"></i>
    <i class="venus double icon"></i>
    <i class="venus mars icon"></i>
  </div>
));

stories.add('Hands & Gestures', () => (
  <div className='ui segment'>
    <i class="hand lizard icon"></i>
    <i class="hand lizard outline icon"></i>
    <i class="hand paper icon"></i>
    <i class="hand paper outline icon"></i>
    <i class="hand peace icon"></i>
    <i class="hand peace outline icon"></i>
    <i class="hand point down icon"></i>
    <i class="hand point down outline icon"></i>
    <i class="hand point left icon"></i>
    <i class="hand point left outline icon"></i>
    <i class="hand point right icon"></i>
    <i class="hand point right outline icon"></i>
    <i class="hand point up icon"></i>
    <i class="hand point up outline icon"></i>
    <i class="hand pointer icon"></i>
    <i class="hand pointer outline icon"></i>
    <i class="hand rock icon"></i>
    <i class="hand rock outline icon"></i>
    <i class="hand scissors icon"></i>
    <i class="hand scissors outline icon"></i>
    <i class="hand spock icon"></i>
    <i class="hand spock outline icon"></i>
    <i class="handshake icon"></i>
    <i class="handshake outline icon"></i>
    <i class="thumbs down icon"></i>
    <i class="thumbs down outline icon"></i>
    <i class="thumbs up icon"></i>
    <i class="thumbs up outline icon"></i>
  </div>
));

stories.add('Health', () => (
  <div className='ui segment'>
    <i class="ambulance icon"></i>
    <i class="h square icon"></i>
    <i class="heart icon"></i>
    <i class="heart outline icon"></i>
    <i class="heartbeat icon"></i>
    <i class="hospital icon"></i>
    <i class="hospital outline icon"></i>
    <i class="medkit icon"></i>
    <i class="plus square icon"></i>
    <i class="plus square outline icon"></i>
    <i class="stethoscope icon"></i>
    <i class="user md icon"></i>
    <i class="wheelchair icon"></i>
  </div>
));

stories.add('Images', () => (
  <div className='ui segment'>
    <i class="adjust icon"></i>
    <i class="bolt icon"></i>
    <i class="camera icon"></i>
    <i class="camera retro icon"></i>
    <i class="clone icon"></i>
    <i class="clone outline icon"></i>
    <i class="compress icon"></i>
    <i class="expand icon"></i>
    <i class="eye icon"></i>
    <i class="eye dropper icon"></i>
    <i class="eye slash icon"></i>
    <i class="eye slash outline icon"></i>
    <i class="file image icon"></i>
    <i class="file image outline icon"></i>
    <i class="film icon"></i>
    <i class="id badge icon"></i>
    <i class="id badge outline icon"></i>
    <i class="id card icon"></i>
    <i class="id card outline icon"></i>
    <i class="image icon"></i>
    <i class="image outline icon"></i>
    <i class="images icon"></i>
    <i class="images outline icon"></i>
    <i class="sliders horizontal icon"></i>
    <i class="tint icon"></i>
  </div>
));

stories.add('Interfaces', () => (
  <div className='ui segment'>
    <i class="ban icon"></i>
    <i class="barcode icon"></i>
    <i class="bars icon"></i>
    <i class="beer icon"></i>
    <i class="bell icon"></i>
    <i class="bell outline icon"></i>
    <i class="bell slash icon"></i>
    <i class="bell slash outline icon"></i>
    <i class="bug icon"></i>
    <i class="bullhorn icon"></i>
    <i class="bullseye icon"></i>
    <i class="calculator icon"></i>
    <i class="calendar icon"></i>
    <i class="calendar outline icon"></i>
    <i class="calendar alternate icon"></i>
    <i class="calendar alternate outline icon"></i>
    <i class="calendar check icon"></i>
    <i class="calendar check outline icon"></i>
    <i class="calendar minus icon"></i>
    <i class="calendar minus outline icon"></i>
    <i class="calendar plus icon"></i>
    <i class="calendar plus outline icon"></i>
    <i class="calendar times icon"></i>
    <i class="calendar times outline icon"></i>
    <i class="certificate icon"></i>
    <i class="check icon"></i>
    <i class="check circle icon"></i>
    <i class="check circle outline icon"></i>
    <i class="check square icon"></i>
    <i class="check square outline icon"></i>
    <i class="circle icon"></i>
    <i class="circle outline icon"></i>
    <i class="clipboard icon"></i>
    <i class="clipboard outline icon"></i>
    <i class="clone icon"></i>
    <i class="clone outline icon"></i>
    <i class="cloud icon"></i>
    <i class="cloud download icon"></i>
    <i class="cloud upload icon"></i>
    <i class="coffee icon"></i>
    <i class="cog icon"></i>
    <i class="cogs icon"></i>
    <i class="copy icon"></i>
    <i class="copy outline icon"></i>
    <i class="cut icon"></i>
    <i class="database icon"></i>
    <i class="dot circle icon"></i>
    <i class="dot circle outline icon"></i>
    <i class="download icon"></i>
    <i class="edit icon"></i>
    <i class="edit outline icon"></i>
    <i class="ellipsis horizontal icon"></i>
    <i class="ellipsis vertical icon"></i>
    <i class="envelope icon"></i>
    <i class="envelope outline icon"></i>
    <i class="envelope open icon"></i>
    <i class="envelope open outline icon"></i>
    <i class="eraser icon"></i>
    <i class="exclamation icon"></i>
    <i class="exclamation circle icon"></i>
    <i class="exclamation triangle icon"></i>
    <i class="external alternate icon"></i>
    <i class="external square alternate icon"></i>
    <i class="eye icon"></i>
    <i class="eye slash icon"></i>
    <i class="eye slash outline icon"></i>
    <i class="file icon"></i>
    <i class="file outline icon"></i>
    <i class="file alternate icon"></i>
    <i class="file alternate outline icon"></i>
    <i class="filter icon"></i>
    <i class="flag icon"></i>
    <i class="flag outline icon"></i>
    <i class="flag checkered icon"></i>
    <i class="folder icon"></i>
    <i class="folder outline icon"></i>
    <i class="folder open icon"></i>
    <i class="folder open outline icon"></i>
    <i class="frown icon"></i>
    <i class="frown outline icon"></i>
    <i class="hashtag icon"></i>
    <i class="heart icon"></i>
    <i class="heart outline icon"></i>
    <i class="history icon"></i>
    <i class="home icon"></i>
    <i class="i cursor icon"></i>
    <i class="info icon"></i>
    <i class="info circle icon"></i>
    <i class="language icon"></i>
    <i class="magic icon"></i>
    <i class="meh icon"></i>
    <i class="meh outline icon"></i>
    <i class="microphone icon"></i>
    <i class="microphone slash icon"></i>
    <i class="minus icon"></i>
    <i class="minus circle icon"></i>
    <i class="minus square icon"></i>
    <i class="minus square outline icon"></i>
    <i class="paste icon"></i>
    <i class="pencil alternate icon"></i>
    <i class="plus icon"></i>
    <i class="plus circle icon"></i>
    <i class="plus square icon"></i>
    <i class="plus square outline icon"></i>
    <i class="qrcode icon"></i>
    <i class="question icon"></i>
    <i class="question circle icon"></i>
    <i class="question circle outline icon"></i>
    <i class="quote left icon"></i>
    <i class="quote right icon"></i>
    <i class="redo icon"></i>
    <i class="redo alternate icon"></i>
    <i class="reply icon"></i>
    <i class="reply all icon"></i>
    <i class="rss icon"></i>
    <i class="rss square icon"></i>
    <i class="save icon"></i>
    <i class="save outline icon"></i>
    <i class="search icon"></i>
    <i class="search minus icon"></i>
    <i class="search plus icon"></i>
    <i class="share icon"></i>
    <i class="share alternate icon"></i>
    <i class="share alternate square icon"></i>
    <i class="share square icon"></i>
    <i class="share square outline icon"></i>
    <i class="shield alternate icon"></i>
    <i class="sign in alternate icon"></i>
    <i class="sign out alternate icon"></i>
    <i class="signal icon"></i>
    <i class="sitemap icon"></i>
    <i class="sliders horizontal icon"></i>
    <i class="smile icon"></i>
    <i class="smile outline icon"></i>
    <i class="sort icon"></i>
    <i class="sort alphabet down icon"></i>
    <i class="sort alphabet up icon"></i>
    <i class="sort amount down icon"></i>
    <i class="sort amount up icon"></i>
    <i class="sort down icon"></i>
    <i class="sort numeric down icon"></i>
    <i class="sort numeric up icon"></i>
    <i class="sort up icon"></i>
    <i class="star icon"></i>
    <i class="star outline icon"></i>
    <i class="star half icon"></i>
    <i class="star half outline icon"></i>
    <i class="sync icon"></i>
    <i class="sync alternate icon"></i>
    <i class="thumbs down icon"></i>
    <i class="thumbs down outline icon"></i>
    <i class="thumbs up icon"></i>
    <i class="thumbs up outline icon"></i>
    <i class="times icon"></i>
    <i class="times circle icon"></i>
    <i class="times circle outline icon"></i>
    <i class="toggle off icon"></i>
    <i class="toggle on icon"></i>
    <i class="trash icon"></i>
    <i class="trash alternate icon"></i>
    <i class="trash alternate outline icon"></i>
    <i class="trophy icon"></i>
    <i class="undo icon"></i>
    <i class="undo alternate icon"></i>
    <i class="upload icon"></i>
    <i class="user icon"></i>
    <i class="user outline icon"></i>
    <i class="user circle icon"></i>
    <i class="user circle outline icon"></i>
    <i class="wifi icon"></i>
  </div>
));

stories.add('Logistics', () => (
  <div className='ui segment'>
    <i class="box icon"></i>
    <i class="boxes icon"></i>
    <i class="clipboard check icon"></i>
    <i class="clipboard list icon"></i>
    <i class="dolly icon"></i>
    <i class="dolly flatbed icon"></i>
    <i class="pallet icon"></i>
    <i class="shipping fast icon"></i>
    <i class="truck icon"></i>
    <i class="warehouse icon"></i>
  </div>
));

stories.add('Maps', () => (
  <div className='ui segment'>
    <i class="ambulance icon"></i>
    <i class="anchor icon"></i>
    <i class="balance scale icon"></i>
    <i class="bath icon"></i>
    <i class="bed icon"></i>
    <i class="beer icon"></i>
    <i class="bell icon"></i>
    <i class="bell outline icon"></i>
    <i class="bell slash icon"></i>
    <i class="bell slash outline icon"></i>
    <i class="bicycle icon"></i>
    <i class="binoculars icon"></i>
    <i class="birthday cake icon"></i>
    <i class="blind icon"></i>
    <i class="bomb icon"></i>
    <i class="book icon"></i>
    <i class="bookmark icon"></i>
    <i class="bookmark outline icon"></i>
    <i class="briefcase icon"></i>
    <i class="building icon"></i>
    <i class="building outline icon"></i>
    <i class="car icon"></i>
    <i class="coffee icon"></i>
    <i class="crosshairs icon"></i>
    <i class="dollar sign icon"></i>
    <i class="eye icon"></i>
    <i class="eye slash icon"></i>
    <i class="eye slash outline icon"></i>
    <i class="fighter jet icon"></i>
    <i class="fire icon"></i>
    <i class="fire extinguisher icon"></i>
    <i class="flag icon"></i>
    <i class="flag outline icon"></i>
    <i class="flag checkered icon"></i>
    <i class="flask icon"></i>
    <i class="gamepad icon"></i>
    <i class="gavel icon"></i>
    <i class="gift icon"></i>
    <i class="glass martini icon"></i>
    <i class="globe icon"></i>
    <i class="graduation cap icon"></i>
    <i class="h square icon"></i>
    <i class="heart icon"></i>
    <i class="heart outline icon"></i>
    <i class="heartbeat icon"></i>
    <i class="home icon"></i>
    <i class="hospital icon"></i>
    <i class="hospital outline icon"></i>
    <i class="image icon"></i>
    <i class="image outline icon"></i>
    <i class="images icon"></i>
    <i class="images outline icon"></i>
    <i class="industry icon"></i>
    <i class="info icon"></i>
    <i class="info circle icon"></i>
    <i class="key icon"></i>
    <i class="leaf icon"></i>
    <i class="lemon icon"></i>
    <i class="lemon outline icon"></i>
    <i class="life ring icon"></i>
    <i class="life ring outline icon"></i>
    <i class="lightbulb icon"></i>
    <i class="lightbulb outline icon"></i>
    <i class="location arrow icon"></i>
    <i class="low vision icon"></i>
    <i class="magnet icon"></i>
    <i class="male icon"></i>
    <i class="map icon"></i>
    <i class="map outline icon"></i>
    <i class="map marker icon"></i>
    <i class="map marker alternate icon"></i>
    <i class="map pin icon"></i>
    <i class="map signs icon"></i>
    <i class="medkit icon"></i>
    <i class="money bill alternate icon"></i>
    <i class="money bill alternate outline icon"></i>
    <i class="motorcycle icon"></i>
    <i class="music icon"></i>
    <i class="newspaper icon"></i>
    <i class="newspaper outline icon"></i>
    <i class="paw icon"></i>
    <i class="phone icon"></i>
    <i class="phone square icon"></i>
    <i class="phone volume icon"></i>
    <i class="plane icon"></i>
    <i class="plug icon"></i>
    <i class="plus icon"></i>
    <i class="plus square icon"></i>
    <i class="plus square outline icon"></i>
    <i class="print icon"></i>
    <i class="recycle icon"></i>
    <i class="road icon"></i>
    <i class="rocket icon"></i>
    <i class="search icon"></i>
    <i class="search minus icon"></i>
    <i class="search plus icon"></i>
    <i class="ship icon"></i>
    <i class="shopping bag icon"></i>
    <i class="shopping basket icon"></i>
    <i class="shopping cart icon"></i>
    <i class="shower icon"></i>
    <i class="street view icon"></i>
    <i class="subway icon"></i>
    <i class="suitcase icon"></i>
    <i class="tag icon"></i>
    <i class="tags icon"></i>
    <i class="taxi icon"></i>
    <i class="thumbtack icon"></i>
    <i class="ticket alternate icon"></i>
    <i class="tint icon"></i>
    <i class="train icon"></i>
    <i class="tree icon"></i>
    <i class="trophy icon"></i>
    <i class="truck icon"></i>
    <i class="tty icon"></i>
    <i class="umbrella icon"></i>
    <i class="university icon"></i>
    <i class="utensil spoon icon"></i>
    <i class="utensils icon"></i>
    <i class="wheelchair icon"></i>
    <i class="wifi icon"></i>
    <i class="wrench icon"></i>
  </div>
));

stories.add('Medical', () => (
  <div className='ui segment'>
    <i class="ambulance icon"></i>
    <i class="band aid icon"></i>
    <i class="dna icon"></i>
    <i class="first aid icon"></i>
    <i class="heart icon"></i>
    <i class="heart outline icon"></i>
    <i class="heartbeat icon"></i>
    <i class="hospital icon"></i>
    <i class="hospital outline icon"></i>
    <i class="hospital symbol icon"></i>
    <i class="pills icon"></i>
    <i class="plus icon"></i>
    <i class="stethoscope icon"></i>
    <i class="syringe icon"></i>
    <i class="thermometer icon"></i>
    <i class="user md icon"></i>
    <i class="weight icon"></i>
  </div>
));

stories.add('Objects', () => (
  <div className='ui segment'>
    <i class="ambulance icon"></i>
    <i class="anchor icon"></i>
    <i class="archive icon"></i>
    <i class="balance scale icon"></i>
    <i class="bath icon"></i>
    <i class="bed icon"></i>
    <i class="beer icon"></i>
    <i class="bell icon"></i>
    <i class="bell outline icon"></i>
    <i class="bicycle icon"></i>
    <i class="binoculars icon"></i>
    <i class="birthday cake icon"></i>
    <i class="bomb icon"></i>
    <i class="book icon"></i>
    <i class="bookmark icon"></i>
    <i class="bookmark outline icon"></i>
    <i class="briefcase icon"></i>
    <i class="bug icon"></i>
    <i class="building icon"></i>
    <i class="building outline icon"></i>
    <i class="bullhorn icon"></i>
    <i class="bullseye icon"></i>
    <i class="bus icon"></i>
    <i class="calculator icon"></i>
    <i class="calendar icon"></i>
    <i class="calendar outline icon"></i>
    <i class="calendar alternate icon"></i>
    <i class="calendar alternate outline icon"></i>
    <i class="camera icon"></i>
    <i class="camera retro icon"></i>
    <i class="car icon"></i>
    <i class="clipboard icon"></i>
    <i class="clipboard outline icon"></i>
    <i class="cloud icon"></i>
    <i class="coffee icon"></i>
    <i class="cog icon"></i>
    <i class="cogs icon"></i>
    <i class="compass icon"></i>
    <i class="compass outline icon"></i>
    <i class="copy icon"></i>
    <i class="copy outline icon"></i>
    <i class="cube icon"></i>
    <i class="cubes icon"></i>
    <i class="cut icon"></i>
    <i class="envelope icon"></i>
    <i class="envelope outline icon"></i>
    <i class="envelope open icon"></i>
    <i class="envelope open outline icon"></i>
    <i class="eraser icon"></i>
    <i class="eye icon"></i>
    <i class="eye dropper icon"></i>
    <i class="fax icon"></i>
    <i class="fighter jet icon"></i>
    <i class="file icon"></i>
    <i class="file outline icon"></i>
    <i class="file alternate icon"></i>
    <i class="file alternate outline icon"></i>
    <i class="film icon"></i>
    <i class="fire icon"></i>
    <i class="fire extinguisher icon"></i>
    <i class="flag icon"></i>
    <i class="flag outline icon"></i>
    <i class="flag checkered icon"></i>
    <i class="flask icon"></i>
    <i class="futbol icon"></i>
    <i class="futbol outline icon"></i>
    <i class="gamepad icon"></i>
    <i class="gavel icon"></i>
    <i class="gem icon"></i>
    <i class="gem outline icon"></i>
    <i class="gift icon"></i>
    <i class="glass martini icon"></i>
    <i class="globe icon"></i>
    <i class="graduation cap icon"></i>
    <i class="hdd icon"></i>
    <i class="hdd outline icon"></i>
    <i class="headphones icon"></i>
    <i class="heart icon"></i>
    <i class="heart outline icon"></i>
    <i class="home icon"></i>
    <i class="hospital icon"></i>
    <i class="hospital outline icon"></i>
    <i class="hourglass icon"></i>
    <i class="hourglass outline icon"></i>
    <i class="image icon"></i>
    <i class="image outline icon"></i>
    <i class="images icon"></i>
    <i class="images outline icon"></i>
    <i class="industry icon"></i>
    <i class="key icon"></i>
    <i class="keyboard icon"></i>
    <i class="keyboard outline icon"></i>
    <i class="laptop icon"></i>
    <i class="leaf icon"></i>
    <i class="lemon icon"></i>
    <i class="lemon outline icon"></i>
    <i class="life ring icon"></i>
    <i class="life ring outline icon"></i>
    <i class="lightbulb icon"></i>
    <i class="lightbulb outline icon"></i>
    <i class="lock icon"></i>
    <i class="lock open icon"></i>
    <i class="magic icon"></i>
    <i class="magnet icon"></i>
    <i class="map icon"></i>
    <i class="map outline icon"></i>
    <i class="map marker icon"></i>
    <i class="map marker alternate icon"></i>
    <i class="map pin icon"></i>
    <i class="map signs icon"></i>
    <i class="medkit icon"></i>
    <i class="microchip icon"></i>
    <i class="microphone icon"></i>
    <i class="mobile icon"></i>
    <i class="mobile alternate icon"></i>
    <i class="money bill alternate icon"></i>
    <i class="money bill alternate outline icon"></i>
    <i class="moon icon"></i>
    <i class="moon outline icon"></i>
    <i class="motorcycle icon"></i>
    <i class="newspaper icon"></i>
    <i class="newspaper outline icon"></i>
    <i class="paint brush icon"></i>
    <i class="paper plane icon"></i>
    <i class="paper plane outline icon"></i>
    <i class="paperclip icon"></i>
    <i class="paste icon"></i>
    <i class="paw icon"></i>
    <i class="pencil alternate icon"></i>
    <i class="phone icon"></i>
    <i class="plane icon"></i>
    <i class="plug icon"></i>
    <i class="print icon"></i>
    <i class="puzzle piece icon"></i>
    <i class="road icon"></i>
    <i class="rocket icon"></i>
    <i class="save icon"></i>
    <i class="save outline icon"></i>
    <i class="search icon"></i>
    <i class="shield alternate icon"></i>
    <i class="shopping bag icon"></i>
    <i class="shopping basket icon"></i>
    <i class="shopping cart icon"></i>
    <i class="shower icon"></i>
    <i class="snowflake icon"></i>
    <i class="snowflake outline icon"></i>
    <i class="space shuttle icon"></i>
    <i class="star icon"></i>
    <i class="star outline icon"></i>
    <i class="sticky note icon"></i>
    <i class="sticky note outline icon"></i>
    <i class="stopwatch icon"></i>
    <i class="subway icon"></i>
    <i class="suitcase icon"></i>
    <i class="sun icon"></i>
    <i class="sun outline icon"></i>
    <i class="tablet icon"></i>
    <i class="tablet alternate icon"></i>
    <i class="tachometer alternate icon"></i>
    <i class="tag icon"></i>
    <i class="tags icon"></i>
    <i class="taxi icon"></i>
    <i class="thumbtack icon"></i>
    <i class="ticket alternate icon"></i>
    <i class="train icon"></i>
    <i class="trash icon"></i>
    <i class="trash alternate icon"></i>
    <i class="trash alternate outline icon"></i>
    <i class="tree icon"></i>
    <i class="trophy icon"></i>
    <i class="truck icon"></i>
    <i class="tv icon"></i>
    <i class="umbrella icon"></i>
    <i class="university icon"></i>
    <i class="unlock icon"></i>
    <i class="unlock alternate icon"></i>
    <i class="utensil spoon icon"></i>
    <i class="utensils icon"></i>
    <i class="wheelchair icon"></i>
    <i class="wrench icon"></i>
  </div>
));

stories.add('Payments & Shopping', () => (
  <div className='ui segment'>
    <i class="bell icon"></i>
    <i class="bell outline icon"></i>
    <i class="bookmark icon"></i>
    <i class="bookmark outline icon"></i>
    <i class="bullhorn icon"></i>
    <i class="camera icon"></i>
    <i class="camera retro icon"></i>
    <i class="cart arrow down icon"></i>
    <i class="cart plus icon"></i>
    <i class="certificate icon"></i>
    <i class="credit card icon"></i>
    <i class="credit card outline icon"></i>
    <i class="gem icon"></i>
    <i class="gem outline icon"></i>
    <i class="gift icon"></i>
    <i class="handshake icon"></i>
    <i class="handshake outline icon"></i>
    <i class="heart icon"></i>
    <i class="heart outline icon"></i>
    <i class="key icon"></i>
    <i class="shopping bag icon"></i>
    <i class="shopping basket icon"></i>
    <i class="shopping cart icon"></i>
    <i class="star icon"></i>
    <i class="star outline icon"></i>
    <i class="tag icon"></i>
    <i class="tags icon"></i>
    <i class="thumbs down icon"></i>
    <i class="thumbs down outline icon"></i>
    <i class="thumbs up icon"></i>
    <i class="thumbs up outline icon"></i>
    <i class="trophy icon"></i>
  </div>
));


stories.add('Shapes', () => (
  <div className='ui segment'>
    <i class="bookmark icon"></i>
    <i class="bookmark outline icon"></i>
    <i class="calendar icon"></i>
    <i class="calendar outline icon"></i>
    <i class="certificate icon"></i>
    <i class="circle icon"></i>
    <i class="circle outline icon"></i>
    <i class="cloud icon"></i>
    <i class="comment icon"></i>
    <i class="comment outline icon"></i>
    <i class="file icon"></i>
    <i class="file outline icon"></i>
    <i class="folder icon"></i>
    <i class="folder outline icon"></i>
    <i class="heart icon"></i>
    <i class="heart outline icon"></i>
    <i class="map marker icon"></i>
    <i class="play icon"></i>
    <i class="square icon"></i>
    <i class="square outline icon"></i>
    <i class="star icon"></i>
    <i class="star outline icon"></i>
  </div>
));

stories.add('Spinners', () => (
  <div className='ui segment'>
    <i class="asterisk icon"></i>
    <i class="certificate icon"></i>
    <i class="circle notch icon"></i>
    <i class="cog icon"></i>
    <i class="compass icon"></i>
    <i class="compass outline icon"></i>
    <i class="crosshairs icon"></i>
    <i class="life ring icon"></i>
    <i class="life ring outline icon"></i>
    <i class="snowflake icon"></i>
    <i class="snowflake outline icon"></i>
    <i class="spinner icon"></i>
    <i class="sun icon"></i>
    <i class="sun outline icon"></i>
    <i class="sync icon"></i>
  </div>
));

stories.add('Sports', () => (
  <div className="ui segment">
    <i class="baseball ball icon"></i>
    <i class="basketball ball icon"></i>
    <i class="bowling ball icon"></i>
    <i class="football ball icon"></i>
    <i class="futbol icon"></i>
    <i class="futbol outline icon"></i>
    <i class="golf ball icon"></i>
    <i class="hockey puck icon"></i>
    <i class="quidditch icon"></i>
    <i class="table tennis icon"></i>
    <i class="volleyball ball icon"></i>
  </div>
));

stories.add('Status', () => (
  <div className='ui segment'>
    <i class="ban icon"></i>
    <i class="battery empty icon"></i>
    <i class="battery full icon"></i>
    <i class="battery half icon"></i>
    <i class="battery quarter icon"></i>
    <i class="battery three quarters icon"></i>
    <i class="bell icon"></i>
    <i class="bell outline icon"></i>
    <i class="bell slash icon"></i>
    <i class="bell slash outline icon"></i>
    <i class="calendar icon"></i>
    <i class="calendar outline icon"></i>
    <i class="calendar alternate icon"></i>
    <i class="calendar alternate outline icon"></i>
    <i class="calendar check icon"></i>
    <i class="calendar check outline icon"></i>
    <i class="calendar minus icon"></i>
    <i class="calendar minus outline icon"></i>
    <i class="calendar plus icon"></i>
    <i class="calendar plus outline icon"></i>
    <i class="calendar times icon"></i>
    <i class="calendar times outline icon"></i>
    <i class="cart arrow down icon"></i>
    <i class="cart plus icon"></i>
    <i class="exclamation icon"></i>
    <i class="exclamation circle icon"></i>
    <i class="exclamation triangle icon"></i>
    <i class="eye icon"></i>
    <i class="eye slash icon"></i>
    <i class="eye slash outline icon"></i>
    <i class="file icon"></i>
    <i class="file outline icon"></i>
    <i class="file alternate icon"></i>
    <i class="file alternate outline icon"></i>
    <i class="folder icon"></i>
    <i class="folder outline icon"></i>
    <i class="folder open icon"></i>
    <i class="folder open outline icon"></i>
    <i class="info icon"></i>
    <i class="info circle icon"></i>
    <i class="lock icon"></i>
    <i class="lock open icon"></i>
    <i class="minus icon"></i>
    <i class="minus circle icon"></i>
    <i class="minus square icon"></i>
    <i class="minus square outline icon"></i>
    <i class="plus icon"></i>
    <i class="plus circle icon"></i>
    <i class="plus square icon"></i>
    <i class="plus square outline icon"></i>
    <i class="question icon"></i>
    <i class="question circle icon"></i>
    <i class="question circle outline icon"></i>
    <i class="shield alternate icon"></i>
    <i class="shopping cart icon"></i>
    <i class="sign in alternate icon"></i>
    <i class="sign out alternate icon"></i>
    <i class="thermometer empty icon"></i>
    <i class="thermometer full icon"></i>
    <i class="thermometer half icon"></i>
    <i class="thermometer quarter icon"></i>
    <i class="thermometer three quarters icon"></i>
    <i class="thumbs down icon"></i>
    <i class="thumbs down outline icon"></i>
    <i class="thumbs up icon"></i>
    <i class="thumbs up outline icon"></i>
    <i class="toggle off icon"></i>
    <i class="toggle on icon"></i>
    <i class="unlock icon"></i>
    <i class="unlock alternate icon"></i>
  </div>
));

stories.add('Users & People', () => (
  <div className='ui segment'>
    <i class="address book icon"></i>
    <i class="address book outline icon"></i>
    <i class="address card icon"></i>
    <i class="address card outline icon"></i>
    <i class="bed icon"></i>
    <i class="blind icon"></i>
    <i class="child icon"></i>
    <i class="female icon"></i>
    <i class="frown icon"></i>
    <i class="frown outline icon"></i>
    <i class="id badge icon"></i>
    <i class="id badge outline icon"></i>
    <i class="id card icon"></i>
    <i class="id card outline icon"></i>
    <i class="male icon"></i>
    <i class="meh icon"></i>
    <i class="meh outline icon"></i>
    <i class="power off icon"></i>
    <i class="smile icon"></i>
    <i class="smile outline icon"></i>
    <i class="street view icon"></i>
    <i class="user icon"></i>
    <i class="user outline icon"></i>
    <i class="user circle icon"></i>
    <i class="user circle outline icon"></i>
    <i class="user md icon"></i>
    <i class="user plus icon"></i>
    <i class="user secret icon"></i>
    <i class="user times icon"></i>
    <i class="users icon"></i>
    <i class="wheelchair icon"></i>
  </div>
));

stories.add('Vehicles', () => (
  <div className='ui segment'>
    <i class="ambulance icon"></i>
    <i class="bicycle icon"></i>
    <i class="bus icon"></i>
    <i class="car icon"></i>
    <i class="fighter jet icon"></i>
    <i class="motorcycle icon"></i>
    <i class="paper plane icon"></i>
    <i class="paper plane outline icon"></i>
    <i class="plane icon"></i>
    <i class="rocket icon"></i>
    <i class="ship icon"></i>
    <i class="shopping cart icon"></i>
    <i class="space shuttle icon"></i>
    <i class="subway icon"></i>
    <i class="taxi icon"></i>
    <i class="train icon"></i>
    <i class="truck icon"></i>
    <i class="wheelchair icon"></i>
  </div>
));


stories.add('Writing', () => (
  <div className='ui segment'>
    <i class="archive icon"></i>
    <i class="book icon"></i>
    <i class="bookmark icon"></i>
    <i class="bookmark outline icon"></i>
    <i class="edit icon"></i>
    <i class="edit outline icon"></i>
    <i class="envelope icon"></i>
    <i class="envelope outline icon"></i>
    <i class="envelope open icon"></i>
    <i class="envelope open outline icon"></i>
    <i class="eraser icon"></i>
    <i class="file icon"></i>
    <i class="file outline icon"></i>
    <i class="file alternate icon"></i>
    <i class="file alternate outline icon"></i>
    <i class="folder icon"></i>
    <i class="folder outline icon"></i>
    <i class="folder open icon"></i>
    <i class="folder open outline icon"></i>
    <i class="keyboard icon"></i>
    <i class="keyboard outline icon"></i>
    <i class="newspaper icon"></i>
    <i class="newspaper outline icon"></i>
    <i class="paper plane icon"></i>
    <i class="paper plane outline icon"></i>
    <i class="paperclip icon"></i>
    <i class="paragraph icon"></i>
    <i class="pen square icon"></i>
    <i class="pencil alternate icon"></i>
    <i class="quote left icon"></i>
    <i class="quote right icon"></i>
    <i class="sticky note icon"></i>
    <i class="sticky note outline icon"></i>
    <i class="thumbtack icon"></i>
  </div>
));

